import { fn } from 'jest-mock';

// Used to avoid console.log output generated by fetchNewTypes
console.log = fn(); // eslint-disable-line no-console

describe('fetchNewTypes generation tests', () => {
  it('should be called', () => {
    expect(true).toBe(true);
  });
});